version: "3.9"

services:
  mysql:
    image: mysql:8
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes

  consumer:
    build: ./consumer
    container_name: api-log-consumer
    depends_on:
      - kafka
      - mysql
    environment:
      - KAFKA_BROKER=kafka:9092
    env_file:
      - .env

  producer:
    build: ./producer
    container_name: api-log-producer
    depends_on:
      - kafka 
    environment:
      - KAFKA_BROKER=kafka:9092
    env_file:
      - .env
    ports:
      - "8000:8000"